#!/bin/bash

usage() {
    cat <<EOF
Renders a markdown file into html using pandoc

Usage:
    $1 /path/to/input.md  # generates /path/to/input.html
    $1 /path/to/input.md /another/path/to/output.html
EOF
}

input="$1"
if [[ ! -e "$input" ]]; then  # shows usage when $input doesn't exist
    usage $(basename "$0")
    exit 1
fi

output="$2"
if [[ -z "$output" ]]; then
    output="${input%.*}".html
fi

root=$(dirname $(realpath "${BASH_SOURCE[0]}"))
static="$root"/static

mathjax_js="$root/mathjax/MathJax.js?config=TeX-AMS_CHTML-full"
mathjax_incl="$static"/mathjax.html

# https://stackoverflow.com/a/31926346
export hljs="$root"/highlightjs/build
hljs_incl=`envsubst < "$static"/highlightjs.html`
hljs_css="$hljs"/styles/atom-one-light.min.css

pandoc --standalone --from markdown --to html \
    --template "$static"/pandoc.html --css "$static"/pandoc.css \
    --mathjax="$mathjax_js" -H "$mathjax_incl" \
    --filter "$root"/pandoc-eqref/pandoc-eqref \
    --no-highlight --css "$hljs_css" -V include-after="$hljs_incl" \
    "$input" > "$output"
